services:
  - type: web
    name: ver-ipin-ucunu
    runtime: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
